site_name: IT Journey
site_description: "This website has two purposes: introducing myself and talking about passionating IT-related stuff :)"
site_author: Jordan Breton
site_dir: ../generated
site_url: https://it-journey.tech
copyright: >
  Copyright &copy; 2023 Jordan Breton –
  <a href="#__consent">Change cookie settings</a>
repo_name: 'IT Journey (Mirror)'
repo_url: 'https://github.com/jordan-breton/it-journey-sources'

nav:
  - Home: 'index.md'
  - About:
      - 'about/index.md'
      - Skills: 'about/skill-set.md'
      - History: 'about/history.md'
  - Blog:
    - blog/index.md

theme:
  name: 'material'
  logo: './assets/images/logo-xs.png'
  favicon: './assets/images/logo-xs.png'
  language: 'en'
  custom_dir: overrides
  features:
    #- announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    #- navigation.instant
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - toc.follow
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to bright mode

extra:
  analytics:
    feedback:
      title: Did you like this content?
      ratings:
        - icon: material/heart
          name: Yes, I would want to see more of this!
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: Not my cup of tea :/
          data: 0
          note: >-
            Thanks for your feedback! Feels free to reach me about it using my 
            <a 
              href="https://github.com/jordan-breton/it-journey-website-giscus/issues/new/?title=[Feedback]+{title}+-+{url}" 
              target="_blank"
              rel="noopener"
            >
                feedback form
            </a>.
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the relevance of my content and whether users find what they're
      searching for. With your consent, you're helping me to create better content.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jordan-breton-281088267/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JordanBretonIT
    - icon: fontawesome/brands/github
      link: https://github.com/jordan-breton
    - icon: fontawesome/brands/gitlab
      link: https://framagit.org/

extra_css:
  - assets/css/style.css

plugins:
  - meta
  - tags
  - typeset
  - privacy:
      external_assets_exclude:
        - cdn.jsdelivr.net/npm/mathjax@3/*
        - giscus.app/*
  #- optimize
  - search:
      lang: en
  - social
  - blog:
      post_excerpt: required
      draft_if_future_date: false
  - glightbox
  - git-committers:
      repository: jordan-breton/it-journey-sources
      branch: main
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:
        - contact.md
        - index.md
        - blog/*
  - rss:
      match_path: blog/posts/.*
      comments_path: "#__comments"
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_anchors: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: ['snippets/']
      check_paths: true
      auto_append:
        - includes/glossary.md
  - pymdownx.progressbar
  - abbr
  - toc:
      title: Summary
      permalink: true
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - tables
