site_name: IT Journey
site_description: "So many years ago, I saw my first digital device. It was a Casio SF-3300ER that didn't even work! But my curiosity toward IT started there, and grown with me :)"
site_author: Jordan Breton
site_dir: ../website
copyright: >
  Copyright &copy; 2023 Jordan Breton –
  <a href="#__consent">Change cookie settings</a>
repo_name: 'IT Journey Repository (placeholder)'
repo_url: 'https://github.com/jordan-breton/it-journey-website-giscus'

nav:
  - Home:
    - 'index.md'
  - Blog:
    - blog/index.md

theme:
  name: 'material'
  logo: 'assets/images/logo.xs.png'
  favicon: 'assets/images/logo.xs.png'
  language: 'en'
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.code.annotate
    - content.tooltips
    - navigation.tracking
    - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.path
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - toc.follow
  palette:
    - primary: deep purple
    - accent: amber
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  analytics:
    feedback:
      title: Did you like this content?
      ratings:
        - icon: material/heart
          name: Yes, I would want to see more of this!
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/heart-broken
          name: Not my cup of tea :/
          data: 0
          note: >-
            Thanks for your feedback! Feels free to reach me about it using my 
            <a 
              href="https://github.com/jordan-breton/it-journey-website-giscus/issues/new/?title=[Feedback]+{title}+-+{url}" 
              target="_blank"
              rel="noopener"
            >
                feedback form
            </a>.
  consent:
    title: Cookie consent
    description: >-
      I use cookies to recognize your repeated visits and preferences, as well
      as to measure the relevance of my content and whether users find what they're
      searching for. With your consent, you're helping me to create better content.

extra_css:
  - assets/css/style.css

plugins:
  - meta
  - tags
  - typeset
  - privacy
  - optimize
  - search:
      lang: en
  - social
  - blog
  - glightbox
  - git-authors
  - git-revision-date-localized:
      type: datetime
      enable_creation_date: true
      fallback_to_build_date: true

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_anchors: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: ['./docs']
      check_paths: true
  - pymdownx.progressbar
  - abbr
  - toc:
      title: On this page
      permalink: true
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - footnotes
  - tables
